### ISSUE TITLE
Font-face mist font-display swap

### ISSUE THREAD

**Issue by slimluccii** [Stefan-Espant/connecting-people-realtime-web-app-oba#2]
https://github.com/Stefan-Espant/connecting-people-realtime-web-app-oba/blob/7e70f0b4103388c62ec50f655cf32ed33c5c62c9/public/style/main.css#L60

Voeg tussen de `@font-face {}` `font-display: swap;` toe. Dit zorgt ervoor dat wanneer je fonts nog niet ingeladen zijn de website je systeem fonts als fallback gebruikt. Dit voorkomt dat je bij het laden transparante tekst hebt.

**Comment by Stefan-Espant** [comment]
Toegepast op de twee fonts
